# -*- coding: utf-8 -*-
"""APP_MOCIBA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGQncSPu_qhobJxN7SB1YRz2FyjAjb4Q
"""


import streamlit as st
import pandas as pd
import requests
import io

# --- Grupo 1: Uso de medidas de seguridad
uso_medidas_de_seguridad = {
    "P1": "En la ciudad"
}

# --- Grupo 2: Medidas de seguridad
medidas_de_seguridad = {
    "P2_1": "crear o poner contraseñas (claves, huella digital, patrón, etcétera)",
    "P2_2": "Instalar o actualizar programas antivirus, cortafuegos o antiespías",
    "P2_3": "Bloquear ventanas emergentes del navegador",
    "P2_4": "Cambiar periódicamente las contraseñas.",
    "P2_5": "No ingresar a sitios web inseguros o páginas desconocidas",
    "P2_6": "No abrir ni guardar archivos que envían personas desconocidas",
    "P2_7": "No publicar su correo o número telefónico en redes sociales",
    "P2_8": "Otra"
}

@st.cache_data
def cargar_datos_base():
    file_ids = [
        "1ojZcLZost0BM00yCGN8OLnu7XYyLpEYr"
    ]

    columnas = (
        [
            "ANIO",
            "CVE_ENT",
            "NOM_ENT",
            "SEXO",
            "FACTOR"
        ]
        + list(uso_medidas_de_seguridad.keys())
        + list(medidas_de_seguridad.keys())
    )

    dfs = []

    for file_id in file_ids:
        # Método más robusto para descargar de Google Drive
        url = f"https://drive.google.com/uc?export=download&id={file_id}"

        session = requests.Session()
        response = session.get(url, stream=True)

        # Manejar confirmación de Google Drive si es necesario
        token = None
        for key, value in response.cookies.items():
            if key.startswith('download_warning'):
                token = value
                break

        if token:
            params = {'confirm': token}
            response = session.get(url, params=params, stream=True)

        df_temp = pd.read_csv(
            io.StringIO(response.content.decode("latin1")),
            encoding="latin1",
            usecols=columnas,
            low_memory=False
        )
        dfs.append(df_temp)

    return pd.concat(dfs, ignore_index=True)

df = cargar_datos_base()

st.title("📊 MOCIBA")

tipo_variable = st.radio(
    "Seleccione el indicador",
    [
        "Uso de medidas de seguridad",
        "Medidas de seguridad"
    ]
)

if tipo_variable == "Uso de medidas de seguridad":
    opciones = uso_medidas_de_seguridad
else:
    opciones = medidas_de_seguridad

variable = st.selectbox(
    "Seleccione la variable",
    list(opciones.values())
)

variable_col = [k for k, v in opciones.items() if v == variable][0]

sexo = st.selectbox(
    "Sexo",
    [
        "Total",
        "Hombres",
        "Mujeres"
    ]
)

estado = st.selectbox(
    "Entidad",
    ["NACIONAL"] + sorted(df["NOM_ENT"].unique())
)

def calcular_porcentaje(df, variable, sexo, estado):
    # Filtrar por sexo
    if sexo == "Hombres":
        df_filtrado = df[df["SEXO"] == 1].copy()
    elif sexo == "Mujeres":
        df_filtrado = df[df["SEXO"] == 2].copy()
    else:
        df_filtrado = df[df["SEXO"].isin([1, 2])].copy()

    # Filtrar por estado ANTES del groupby (más eficiente)
    if estado != "NACIONAL":
        df_filtrado = df_filtrado[df_filtrado["NOM_ENT"] == estado]

    # Calcular porcentajes por año de forma más robusta
    resultados = []

    for anio, grupo in df_filtrado.groupby("ANIO"):
        # Numerador: Factor de quienes respondieron 1 (Sí)
        numerador = grupo.loc[grupo[variable] == 1, "FACTOR"].sum()

        # Denominador: Factor de quienes respondieron 1 o 2 (Sí o No)
        denominador = grupo.loc[grupo[variable].isin([1, 2]), "FACTOR"].sum()

        # Calcular porcentaje (evitar división por cero)
        if denominador > 0:
            porcentaje = (numerador / denominador) * 100
        else:
            porcentaje = 0

        resultados.append({
            "ANIO": anio,
            "PORCENTAJE": porcentaje
        })

    return pd.DataFrame(resultados)

resultado = calcular_porcentaje(df, variable_col, sexo, estado)

st.subheader(variable)
st.dataframe(resultado)

st.line_chart(
    resultado.set_index("ANIO")["PORCENTAJE"]
)
